config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :latest, :popular
    end
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      get :followings, :followers, :likes
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'

  with_options presence: true do
    validates :user_id
    validates :follower_id
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:follower])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.relationships.find(params[:id]).follower
    current_user.unfollow(params[:id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_relationship.html.erb
<% if user_signed_in? && current_user.id != @user.id %>
  <% if current_user.following?(@user) %>
    <%= button_to "フォロー中", relationship_path(current_user.relationships.find_by(follower: @user)), method: :delete, class: "btn btn-primary", remote: true %>
  <% else %>
    <%= button_to "フォロー", relationships_path(follower: @user), method: :post, class: "btn btn-outline-primary", remote: true %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$('#relationship_<%= @user.id %>').html("<%= j(render partial: 'relationships/relationship', locals: { user: @user }) %>");

app/views/relationships/destroy.js.erb
$('#relationship_<%= @user.id %>').html("<%= j(render partial: 'relationships/relationship', locals: { user: @user }) %>");