config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :latest, :popular
    end
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      get :followings, :followers, :likes
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :post_params, only: [:create, :destroy]

  def create
    Like.create(user_id: current_user.id, post_id: @post.id)
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: @post.id)
    like.destroy
  end

  private

  def post_params
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if !user_signed_in? %>
  <i class="fa fa-heart like-btn"></i>
  <%= post.likes.length %>
<% elsif current_user.liked_by?(post.id) %>
  <%= link_to post_like_path(post, post.likes), class: "like-link", method: :delete, remote: true do %>
    <i class="fa fa-heart unlike-btn"></i>
  <% end %>
  <%= post.likes.length %>
<% else %>
  <%= link_to post_likes_path(post), class: "like-link", method: :post, remote: true do %>
    <i class="fa fa-heart like-btn"></i>
  <% end %>
  <%= post.likes.length %>
<% end %>

app/views/likes/create.js.erb
$('#like_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: { post: @post }) %>");

app/views/likes/destroy.js.erb
$('#like_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: { post: @post }) %>");