config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :latest, :popular
    end
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      get :followings, :followers, :likes
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user

  validates :nickname, presence: true

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i, message: 'Include both letters and numbers' }

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    relationships.create(follower: user_id)
  end

  def unfollow(relationship_id)
    relationships.find(relationship_id).destroy!
  end

  def self.search(search)
    if search != ''
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :show, :likes, :followings, :followers]
  before_action :set_user, only: [:edit, :update, :show, :likes, :followings, :followers]
  before_action :move_to_index, only: [:edit, :update]

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def likes
    likes = Like.where(user_id: @user).pluck(:post_id)
    @like_posts = Post.find(likes)
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def search
    @users = User.search(params[:keyword])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :avatar, :password)
  end

  def move_to_index
    redirect_to root_path unless @user.id == current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage.html.erb
<section class="latest-box">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0"><%= user.nickname %>さんのマイページ</h4>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-4 p-2">
        <div class="container">
          <ul class="list-group text-center">
            <li class="list-group-item"><%= link_to "マイページ", user_path(user), class: "text-dark text-decoration-none" %></li>
            <% if (current_user == user) || (current_user.following?(user)) && (user.following?(current_user)) %>
              <li class="list-group-item"><%= link_to "お気に入り", likes_user_path(user), class: "text-dark text-decoration-none" %></li>
            <% end %>
            <li class="list-group-item"><%= link_to "フォロー", followings_user_path(user), class: "text-dark text-decoration-none" %></li>
            <li class="list-group-item"><%= link_to "フォロワー", followers_user_path(user), class: "text-dark text-decoration-none" %></li>
            <% if user.id == current_user.id %>
              <li class="list-group-item"><%= link_to "アカウント編集", edit_user_path(user.id), class: "text-dark text-decoration-none" %></li>
              <li class="list-group-item"><%= link_to "ユーザー検索", search_users_path, class: "text-dark text-decoration-none" %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-12 col-lg-5 p-2">
        <div class="container">
          <div class="profile-box">
            <div class="row justify-content-center text-center">
              <div class="col-4 col-lg-3">
                <% if user.avatar? %>
                  <%= image_tag user.avatar.url %>
                <% else %>
                  <i class="fas fa-user"></i>
                <% end %>
              </div>
            </div>
            <div class="row justify-content-center p-3">
              <div class="col-12 text-center">
                <%= user.nickname %>
              </div>
              <div class="col-12 text-end">
                <div id = "relationship_<%= user.id %>">
                  <%= render partial: "relationships/relationship", locals: { user: user } %>
                </div>
              </div>
            </div>
            <div class="row text-center text-secondary pt-3">
              <div class="col-4">
                <%= user.posts.length %><br>投稿
              </div>
              <div class="col-4">
                <%= user.followings.length %><br>フォロー
              </div>
              <div class="col-4">
                <%= user.followers.length %><br>フォロワー
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<div class="container">
  <div class="row my-5 justify-content-center">
    <div class="col-12 col-md-6 col-lg-4 p-2">
      <div class="devise-box">
        <div class="container">
          <div class="row justify-content-center">
            <%= form_with model: @user, local: true do |f|%>
            <%= render 'layouts/user_error_messages', model: f.object %>
              <h2>アカウントの編集</h2>
              <div class="nickname-box col-12 mb-3">
                <%= f.label :nickname %><br />
                <%= f.text_field :nickname, autofocus: true, maxlength: "20" %>
              </div>
              <div class="email-box col-12 mb-3">
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
              </div>
              <div class="password-box col-12 mb-2">
                <%= f.label :password %> <i>(6文字以上入力してください)</i><br />
                <%= f.password_field :password, autocomplete: "new-password" %>
              </div>
              <div class="password-box col-12 mb-3">
                <%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
              </div>
              <div class="password-box col-12 mb-3">
                <%= f.label :current_password %><br />
                <%= f.password_field :current_password, autocomplete: "current-password" %>
              </div>
              <div class="field col-12 mb-4">
                <%= f.label :プロフィール画像 %>
                <%= f.file_field :avatar %>
              </div>
              <div class="login-box col-12 pt-4 mb-5">
                <%= f.submit "更新" %>
              </div>
              <div class="col-12 pt-4 mb-2 text-end">
                <%= link_to "マイページに戻る", user_path(@user), class: "text-decoration-none" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<%= render partial: "mypage", locals: { user: @user } %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">フォロワー一覧</h4>
      </div>
    </div>
    <div class="row row-cols-3">
      <div class="col">
        <% @users.each do |user| %>
          <ul class="list-group list-group-horizontal m-2">
            <% if user.avatar? %>
              <li class="list-group-item col-3 col-lg-2 px-1"><%= link_to image_tag( user.avatar.url ), user_path(user) %></li>
            <% else %>
              <li class="list-group-item">
                <%= link_to user_path(user) do %>
                  <i class="fas fa-user"></i>
                <% end %>
              </li>
            <% end %>
            <li class="list-group-item text-center d-flex align-items-center"><%= link_to user.nickname, user_path(user), class: "text-decoration-none text-dark" %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/followings.html.erb
<%= render partial: "mypage", locals: { user: @user } %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">フォロー一覧</h4>
      </div>
    </div>
    <div class="row row-cols-3">
      <div class="col">
        <% @users.each do |user| %>
          <ul class="list-group list-group-horizontal m-2">
            <% if user.avatar? %>
              <li class="list-group-item col-3 col-lg-2 px-1"><%= link_to image_tag( user.avatar.url ), user_path(user) %></li>
            <% else %>
              <li class="list-group-item">
                <%= link_to user_path(user) do %>
                  <i class="fas fa-user"></i>
                <% end %>
              </li>
            <% end %>
            <li class="list-group-item text-center d-flex align-items-center"><%= link_to user.nickname, user_path(user), class: "text-decoration-none text-dark" %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/likes.html.erb
<section class="latest-box">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0"><%= @user.nickname %>さんのマイページ</h4>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-6 col-lg-4 p-2">
        <div class="container">
            <ul class="list-group text-center">
              <li class="list-group-item"><%= link_to "マイページ", user_path(@user), class: "text-dark text-decoration-none" %></li>
              <li class="list-group-item"><%= link_to "お気に入り", likes_user_path(@user), class: "text-dark text-decoration-none" %></li>
              <li class="list-group-item"><%= link_to "フォロー", followings_user_path(@user), class: "text-dark text-decoration-none" %></li>
              <li class="list-group-item"><%= link_to "フォロワー", followers_user_path(@user), class: "text-dark text-decoration-none" %></li>
              <% if @user.id == current_user.id %>
                <li class="list-group-item"><%= link_to "アカウント編集", edit_user_path(@user.id), class: "text-dark text-decoration-none" %></li>
              <% end %>
            </ul>
        </div>
      </div>
      <div class="col-6 col-lg-5 p-2">
        <div class="container">
          <div class="profile-box">
            <div class="row justify-content-center text-center">
              <div class="col-4 col-lg-3">
                <% if @user.avatar? %>
                  <%= image_tag @user.avatar.url %>
                <% else %>
                  <i class="fas fa-user"></i>
                <% end %>
              </div>
            </div>
            <div class="row justify-content-center pt-3">
              <div class="col-12 text-center">
                <%= @user.nickname %>
                <div id = "relationship_<%= @user.id %>">
                  <%= render partial: "relationships/relationship", locals: { user: @user } %>
                </div>
              </div>
            </div>
            <div class="row text-center text-secondary pt-3">
              <div class="col-4">
                <%= @user.posts.length %><br>投稿
              </div>
              <div class="col-4">
                <%= @user.followings.length %><br>フォロー
              </div>
              <div class="col-4">
                <%= @user.followers.length %><br>フォロワー
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">お気に入り投稿一覧</h4>
        <div>Have a better date for you</div>
      </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "posts/post", collection: @like_posts %>
    </div>
  </div>
</section>

app/views/users/search.html.erb
<section class="index-top">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-7 col-xl-6 text-center">
        <h1 class="mb-5 text-light">よりよいデートを</h1>
        <%= form_with url: search_users_path, local: true, method: :get, class: "d-flex flex-row mb-2 p-1 bg-white shadow-lg input-group rounded-3" do |form| %>
          <%= form.text_field :keyword, placeholder: "検索", class: "form-control form-control-lg rounded-0 border-0 shadow-none" %>
          <%= button_tag type: 'submit', class: "btn btn-secondary rounded-3 flex-shrink-0 shadow-none border-0" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">検索結果</h4>
      </div>
    </div>
    <div class="row row-cols-3">
      <div class="col">
        <% @users.each do |user| %>
          <ul class="list-group list-group-horizontal m-2">
            <% if user.avatar? %>
              <li class="list-group-item col-3 col-lg-2 px-1"><%= link_to image_tag( user.avatar.url ), user_path(user) %></li>
            <% else %>
              <li class="list-group-item">
                <%= link_to user_path(user) do %>
                  <i class="fas fa-user"></i>
                <% end %>
              </li>
            <% end %>
            <li class="list-group-item text-center d-flex align-items-center"><%= link_to user.nickname, user_path(user), class: "text-decoration-none text-dark" %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= render partial: "mypage", locals: { user: @user } %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0"><%= @user.nickname %>さんの投稿一覧</h4>
        <div>Have a better date for you</div>
      </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "posts/post", collection: @posts %>
    </div>
  </div>
</section>