config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :latest, :popular
    end
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      get :followings, :followers, :likes
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :time_slot
  belongs_to :category
  belongs_to :situation
  belongs_to :prefecture
  belongs_to :weather

  with_options presence: true do
    validates :title
    validates :text
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :time_slot_id
    validates :category_id
    validates :situation_id
    validates :prefecture_id
    validates :weather_id
  end

  def self.search(search)
    if search != ''
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.includes(:user)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :latest, :popular]
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @posts = Post.limit(6).order('created_at DESC')
    like_posts = Post.includes(:liked_users).sort { |a, b| b.liked_users.length <=> a.liked_users.length }
    @like_posts = like_posts.first(6)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  def latest
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def popular
    @posts = Post.includes(:liked_users).sort { |a, b| b.liked_users.length <=> a.liked_users.length }
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :image, :time_slot_id, :category_id, :situation_id, :prefecture_id,
                                 :weather_id).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless @post.user.id == current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
  <div class="row mt-3 mb-5 justify-content-center">
    <div class="col-12 col-md-10 col-lg-6 p-2">
      <div class="devise-box">
        <div class="container">
          <div class="row justify-content-center">
            <%= form_with model: @post, local: true do |f| %>
              <%= render 'layouts/post_error_messages', model: f.object %>
              <div class="col-12 mb-3">
                <%= f.label :"タイトルを入力してください" %><br />
                <%= f.text_field :title, placeholder: "タイトル", size: "50", class: "form-control" %>
              </div>
              <div class="col-12 mb-3">
                <%= f.label :"コメントを入力してください" %><br />
                <%= f.text_area :text, placeholder: "コメント", class: "form-control" %>
              </div>
              <div class="col-12 mb-3">
                <%= f.label :"オススメの時間帯を入力してください" %><br />
                <%= f.collection_select(:time_slot_id, TimeSlot.all, :id, :name, {}, {class: "form-control"}) %>
              </div>
              <div class="col-12 mb-3">
                <%= f.label :"カテゴリーを入力してください" %><br />
                <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "form-control"}) %>
              </div>
              <div class="col-12 mb-3">
                <%= f.label :"オススメのシチュエーションを入力してください" %><br />
                <%= f.collection_select(:situation_id, Situation.all, :id, :name, {}, {class: "form-control"}) %>
              </div>
              <div class="col mb-3">
                <%= f.label :"場所を入力してください" %><br />
                <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "form-control"}) %>
              </div>
              <div class="col mb-3">
                <%= f.label :"オススメの天気を入力してください" %><br />
                <%= f.collection_select(:weather_id, Weather.all, :id, :name, {}, {class: "form-control"}) %>
              </div>
              <div class="col-12 mb-4">
                <%= f.label :"画像を選択してください" %><br />
                <%= f.file_field :image %>
              </div>
              <div class="login-box col-12 pt-4 mb-4">
                <%= f.submit " 投稿 " %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-12 col-lg-6 col-xl-4 p-2">
  <div class="post-box">
    <div class="container">
      <div class="row justify-content-center">
        <div class="post-image">
          <%= link_to image_tag( post.image.variant(resize: '320x180') ), post_path(post.id), class: "col-12 justify-content-center text-center px-0" %>
        </div>
        <div class="col text-truncate d-block w-100">
          <%= link_to post.user.nickname, user_path(post.user.id), class: "post-nickname text-start link-secondary" %>
        </div>
        <div class="col text-end">
          <i class="fa fa-heart unlike-btn"></i>
          <%= post.likes.length %>
        </div>
        <div class="col-12 text-center text-reset text-truncate d-block w-100">
          <%= link_to post.title, post_path(post.id), class: "post-title link-dark" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search.html.erb
<section class="index-top">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-7 col-xl-6 text-center">
        <h1 class="mb-5 text-light">よりよいデートを</h1>
        <%= form_with url: search_posts_path, local: true, method: :get, class: "d-flex flex-row mb-2 p-1 bg-white shadow-lg input-group rounded-3" do |form| %>
          <%= form.text_field :keyword, placeholder: "検索", class: "form-control form-control-lg rounded-0 border-0 shadow-none" %>
          <%= button_tag type: 'submit', class: "btn btn-secondary rounded-3 flex-shrink-0 shadow-none border-0" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/edit.html.erb
<div class="container ">
  <div class="row mt-5 text-center">
    <div class="col">
      <h2 class="mb-0">投稿編集</h2>
    </div>
  </div>
</div>

<%= render partial: "form", locals: { form: @post } %>

app/views/posts/index.html.erb
<%= render partial: "search" %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
        <div class="col">
          <h4 class="mb-0">最新の投稿</h4>
          <div>Have a better date for you</div>
        </div>
        <div class="col text-end">
          <%= link_to "すべて見る", latest_posts_path, class: "link-btn link-light" %>
        </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "post", collection: @posts %>
    </div>
  </div>
</section>

<section class="like-box">
  <div class="container">
    <div class="row mb-5 align-items-center">
        <div class="col">
          <h4 class="mb-0">人気の投稿</h4>
          <div>Have a better date for you</div>
        </div>
        <div class="col text-end">
          <%= link_to "すべて見る", popular_posts_path, class: "link-btn link-light" %>
        </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "post", collection: @like_posts %>
    </div>
  </div>
</section>

<section class="latest-box">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 p-2">
        <div class="container">
          <div class="info-box">
            <div class="row justify-content-center">
              <div class="col-11">
                <h4 class="text-center mb-5">Betterでできること</h4>
                <%= image_tag asset_path('image.jpg'), class: "rounded-3" %>
              </div>
            </div>
            <div class="row justify-content-center pt-5">
              <div class="col-2 text-end">
                <div class="info-check"><i class="fas fa-check-circle"></i></div>
              </div>
              <div class="col-10 col-lg-5">
                ユーザー同士の共有で<br>
                <h5>新しいデートスポットが見つかる。</h5>
              </div>
            </div>
            <div class="row justify-content-center pt-3">
              <div class="col-2 text-end">
                <div class="info-check"><i class="fas fa-check-circle"></i></div>
              </div>
              <div class="col-10 col-lg-5">
                カテゴリーやシチュエーションから<br>
                <h5>2人にとって最適な場所が選べる。</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="like-box">
  <div class="container">
    <div class="info-box">
      <div class="row">
        <div class="col-12">
          <h4 class="text-center mb-5">Betterの使い方</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-lg-4 p-2">
          <div class="container">
            <div class="info-box-show">
              <div class="row justify-content-center">
                <div class="col-12">
                  <h5 class="text-center pt-3">探してみる</h5>
                  <%= image_tag asset_path('search.png'), class: "info-image" %>
                  <p class="p-3">毎日たくさんの投稿が共有されています。<br>様々な条件から2人にとって最適な場所を選べます。</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-4 p-2">
          <div class="container">
            <div class="info-box-show">
              <div class="row justify-content-center">
                <div class="col-12">
                  <h5 class="text-center pt-3">行ってみる</h5>
                  <%= image_tag asset_path('date.png'), class: "info-image" %>
                  <p class="p-3">行ってみたい場所を見つけたら、実際にデートを。<br>2人にとって、いつもより良いデートになるかも。</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-4 p-2">
          <div class="container">
            <div class="info-box-show">
              <div class="row justify-content-center">
                <div class="col-12">
                  <h5 class="text-center pt-3">共有する</h5>
                  <%= image_tag asset_path('share.png'), class: "info-image" %>
                  <p class="p-3">オススメの場所やお気に入りの場所などは、ぜひ共有してください。<br>投稿ボタンから、たった5分で簡単に投稿できます。</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/posts/latest.html.erb
<%= render partial: "search" %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">最新の投稿一覧</h4>
        <div>Have a better date for you</div>
      </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "post", collection: @posts %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<div class="container ">
  <div class="row mt-5 text-center">
    <div class="col">
      <h2 class="mb-0">新規投稿</h2>
    </div>
  </div>
</div>

<%= render partial: "form", locals: { form: @post } %>

app/views/posts/popular.html.erb
<%= render partial: "search" %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">人気の投稿一覧</h4>
        <div>Have a better date for you</div>
      </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "post", collection: @posts %>
    </div>
  </div>
</section>

app/views/posts/search.html.erb
<%= render partial: "search" %>

<section class="latest-box">
  <div class="container ">
    <div class="row mb-5 align-items-center">
      <div class="col">
        <h4 class="mb-0">検索結果</h4>
        <div>Have a better date for you</div>
      </div>
    </div>
    <div class="row row-cols-3">
      <%= render partial: "post", collection: @posts %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="latest-box">
  <div class="container">
    <div class="row my-0 text-center">
      <div class="col">
        <h2 class="mb-5">投稿詳細</h2>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mb-5 justify-content-center">
      <div class="col-12 col-lg-6 col-xl-6 p-2">
        <div class="post-box">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 justify-content-center px-0">
                <%= image_tag( @post.image.variant(resize: '320x180') ) %>
              </div>
              <div class="col text-truncate d-block w-100">
                <%= link_to @post.user.nickname, user_path(@post.user.id), class: "post-nickname text-start" %>
              </div>
              <div class="col text-end">
                <div id = "like_<%= @post.id %>">
                  <%= render partial: "likes/like", locals: { post: @post } %>
                </div>
              </div>
              <% if user_signed_in? && current_user.id == @post.user_id %>
                <div class="col-12 text-end">
                  <%= link_to "編集", edit_post_path(@post.id), class: "btn btn-sm btn-outline-secondary text-decoration-none m-2" %>
                  <%= link_to "削除", post_path(@post.id), method: :delete, class: "btn btn-sm btn-outline-secondary text-decoration-none m-2" %>
                  </div>
                </div>
              <% end %>
              <div class="col-12 my-2 p-2 text-center text-reset post-title">
                <%= @post.title %>
              </div>
              <div class="col-12 my-2">
                <div class="post-nickname">コメント</div>
                <div class="col border rounded p-2 text-reset">
                  <%= @post.text %>
                </div>
              </div>
              <div class="col-12 my-2">
                <div class="post-nickname">オススメの時間</div>
                <div class="col border rounded p-2">
                  <%= @post.time_slot.name %>
                </div>
              </div>
              <div class="col-12 my-2">
                <div class="post-nickname">カテゴリー</div>
                <div class="col border rounded p-2">
                  <%= @post.category.name %>
                </div>
              </div>
              <div class="col-12 my-2">
                <div class="post-nickname">オススメのシチュエーション</div>
                <div class="col border rounded p-2">
                  <%= @post.situation.name %>
                </div>
              </div>
              <div class="col-12 my-2">
                <div class="post-nickname">場所</div>
                <div class="col border rounded p-2">
                  <%= @post.prefecture.name %>
                </div>
              </div>
              <div class="col-12 my-2">
                <div class="post-nickname">オススメの天気</div>
                <div class="col border rounded p-2">
                  <%= @post.weather.name %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="latest-box">
  <div class="container">
    <div class="row my-0 text-center">
      <div class="col">
        <h2 class="mb-5">コメント一覧</h2>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mb-5 justify-content-center">
      <div class="col-12 col-lg-6 col-xl-6 p-2">
        <div class="post-box">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 my-3 p-2 text-reset text-truncate d-block w-100 post-title border-bottom">
                  <% if user_signed_in? %>
                  <%= form_with model: [@post, @comment], local: true do |form| %>
                    <%= form.text_area :text, placeholder: "コメントする", class: "form-control" %>
                    <div class="text-end my-2 comment-box">
                      <%= form.submit "送信" %>
                    </div>
                  <% end %>
                <% else %>
                  <div class="text-center text-dark"><p>コメントの投稿には新規登録/ログインが必要です</p></div>
                <% end %>
              </div>
              <% @comments.each do |comment| %>
                <div class="col text-truncate d-block w-100 d-flex align-items-center">
                  <%= link_to @post.user.nickname, user_path(@post.user.id), class: "post-nickname text-start" %>
                </div>
                <% if user_signed_in? && current_user.id == comment.user_id %>
                  <div class="col text-end">
                    <%= link_to "削除", post_comment_path(comment.post.id, comment.id), method: :delete, class: "btn btn-sm btn-outline-secondary text-decoration-none m-1" %>
                  </div>
                <% end %>
                <div class="col-12 border-bottom mb-3 text-break">
                  <%= comment.text %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>